### ISSUE TITLE
Errors When Running dcc-dashboard in Dev Environment

### ISSUE THREAD

**Issue by coverbeck** [BD2KGenomics/dcc-dashboard#37]
There are two problems:

## Wrong DB name

In dev.yml and prod.yml, the bdchart-db has the container name `bd-chart`, but the Python code is accessing the database `bdchart` (no dash).

## Errors 

There are errors in starting up the dcc-service:
```
Traceback (most recent call last):
  File "./app.py", line 18, in <module>
    from oauth2client.crypt import AppIdentityError
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 23, in <module>
    from oauth2client import _pure_python_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_pure_python_crypt.py", line 24, in <module>
    from pyasn1_modules.rfc2459 import Certificate
  File "/usr/local/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
    from pyasn1.type import opentype
ImportError: cannot import name opentype
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by coverbeck** [comment]
PR pending, please assign to me (I don't have rights to assign it).

**Comment by caaespin** [comment]
@coverbeck  done
